package com.example.service

import android.content.Context
import android.content.Intent
import android.provider.CalendarContract
import android.widget.Toast
import com.example.data.Scholarship
import com.example.data.ScholarshipRequirement

object ScholarshipCalendarHelper {

    fun addEventToDeviceCalendar(
        context: Context,
        scholarship: Scholarship,
        requirements: List<ScholarshipRequirement> = emptyList(),
        eventTitle: String,
        eventDateMillis: Long
    ) {
        if (eventDateMillis <= 0) {
            Toast.makeText(context, "No date specified for this event", Toast.LENGTH_SHORT).show()
            return
        }

        val formattedTitle = if (eventTitle.contains("Deadline", ignoreCase = true)) {
            "${scholarship.name} — Application Deadline"
        } else {
            "${scholarship.name}: $eventTitle"
        }

        val amountText = if (scholarship.amount > 0) "${scholarship.currency} %,.0f".format(scholarship.amount) else "Not specified"
        
        val requirementsList = if (requirements.isNotEmpty()) {
            "\n\nRequirements:\n" + requirements.joinToString("\n") { 
                "• ${it.title} [${it.status}]" 
            }
        } else ""

        val notesText = if (scholarship.notes.isNotBlank()) "\n\nNotes:\n${scholarship.notes}" else ""
        val urlText = if (scholarship.applicationUrl.isNotBlank()) "\n\nApplication Portal:\n${scholarship.applicationUrl}" else ""

        val description = """
            Scholarship Provider: ${scholarship.organization}
            Application Status: ${scholarship.status}
            Award Amount: $amountText
            $requirementsList
            $notesText
            $urlText
            
            Generated by GPA Whiz Scholarship Tracker
        """.trimIndent()

        val intent = Intent(Intent.ACTION_INSERT).apply {
            data = CalendarContract.Events.CONTENT_URI
            putExtra(CalendarContract.Events.TITLE, formattedTitle)
            putExtra(CalendarContract.Events.EVENT_LOCATION, scholarship.organization)
            putExtra(CalendarContract.EXTRA_EVENT_BEGIN_TIME, eventDateMillis)
            putExtra(CalendarContract.EXTRA_EVENT_END_TIME, eventDateMillis + (60 * 60 * 1000)) // 1 hour duration
            putExtra(CalendarContract.Events.ALL_DAY, true)
            putExtra(CalendarContract.Events.DESCRIPTION, description)
            flags = Intent.FLAG_ACTIVITY_NEW_TASK
        }

        try {
            context.startActivity(intent)
            Toast.makeText(context, "Opening device calendar...", Toast.LENGTH_SHORT).show()
        } catch (e: Exception) {
            Toast.makeText(context, "Could not open calendar: ${e.message}", Toast.LENGTH_LONG).show()
        }
    }
}
